### ISSUE TITLE
Ensure pecl used matches selected php version

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/packer-templates#270]
We received a report of a `php` build using config like:

``` yaml
language: php
dist: trusty
sudo: required
php: 5.6
before_install: "printf \"autodetect\\n\" | pecl install vendor/imagick-3.1.2.tgz"
# --->8---
```

which resulted in:

``` bash
$ php --version
PHP 5.6.24 (cli) (built: Aug 16 2016 19:43:49) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

and here's the part that's no good, showing that pecl is using the `php-config` from version `7.0.7`:

``` bash
$ printf "autodetect\n" | pecl install vendor/imagick-3.1.2.tgz
15 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
Please provide the prefix of Imagemagick installation [autodetect] : building in /tmp/pear/install/pear-build-travisuzikTF/imagick-3.1.2
running: /tmp/pear/install/imagick/configure --with-php-config=/home/travis/.phpenv/versions/7.0.7/bin/php-config --with-imagick
```

See also: https://github.com/travis-ci/travis-ci/issues/6490
