### ISSUE TITLE
Android image in Trusty-edge: JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by iriberri** [travis-ci/packer-templates#440]
Using `jdk: oraclejdk8` in the new beta Android build seems to be raising the following warning/error, that makes the build fail (for example when calling Gradle):

```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-oracle

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

```

----

**How to reproduce**:
```yaml
language: android
dist: trusty
sudo: required

group: edge

android:
  components:
    - tools
    - platform-tools
    - tools
    
    - android-25
    
    - build-tools-25.0.2
    - extra
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

jdk: oraclejdk8


script:
- gradle
```

**Build example**
https://travis-ci.org/iriberri/android-app/builds/242501177
