### ISSUE TITLE
Update yarn on our Trusty images

### ISSUE THREAD

**Issue by cotsog** [travis-ci/packer-templates#478]
Felix-Antoine (@reel) [reported](https://secure.helpscout.net/conversation/410878849/57939/?folderId=30784) that the `yarn` version is rather old on our Node.js Trusty image.

It's currently at v0.17 while [the latest is v0.27.5](https://github.com/yarnpkg/yarn/releases). The end result is that some newer options (like `--non-interactive`) aren't available out of the box.

Hence, would it be possible to update `yarn` on our images?

Thank you!

**Comment by edmorley** [comment]
The yarn version was updated in travis-ci/travis-cookbooks#866 and afaik a new image released since, so the installed version should already be 0.27.5 - however as seen above it isn't.

@meatballhat any ideas?

**Comment by reel** [comment]
This is the config that is working:

```yaml
---
language: node_js
node_js:
  - "7"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  npm run pretest
cache:
  yarn: true
  directories:
  - node_modules
after_script: npm run coveralls
```
It fails if I remove the `before_install`
