### ISSUE TITLE
Trusty GCE packer-build jobs failing

### ISSUE THREAD

**Issue by edmorley** [travis-ci/packer-templates#610]
Hi! (And long time no pestering on your issue trackers... 😆)

I noticed that our `group: edge` GCE garnet builds were using an image built in December (so are still using yarn 1.3.2 etc), so was hoping to trigger some new edge images.

The last GCE garnet builds (in Jan) failed with:
```
    googlecompute: [2018-01-29T18:37:26+00:00] ERROR: execute[Execute SQL script to create additional superusers] (travis_postgresql::ci_server line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
    googlecompute: ---- Begin output of psql --port=5433 --file=/tmp/packer-chef-solo/local-mode-cache/cache/postgresql_create_superusers.sql ----
    googlecompute: STDOUT:
    googlecompute: STDERR: psql: could not connect to server: No such file or directory
    googlecompute: 	Is the server running locally and accepting
    googlecompute: 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5433"?
    googlecompute: ---- End output of psql --port=5433 --file=/tmp/packer-chef-solo/local-mode-cache/cache/postgresql_create_superusers.sql ----
```
(see https://travis-ci.org/travis-infrastructure/packer-build/jobs/334801518#L2275)

And a new build triggered now (via the technique in https://github.com/travis-ci/packer-templates/issues/543#issuecomment-343255695) failed even sooner with:
```
    googlecompute: Chef::Exceptions::ImmutableAttributeModification
    googlecompute: ------------------------------------------------
    googlecompute: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
    googlecompute:
    googlecompute: Cookbook Trace:
    googlecompute: ---------------
    googlecompute:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/python.rb:139:in `block in from_file'
    googlecompute:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/python.rb:61:in `each'
...
```
(see https://travis-ci.org/travis-infrastructure/packer-build/jobs/376752553#L734)

I'd switch to sardonyx (Xenial) instead, but those `group: edge` builds are also failing.

Many thanks :-)
